/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Element } from "slate";
export namespace Components {
    interface AppRoot {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface PlaitElement {
        "element": Element;
    }
    interface PlaitRichtext {
        "value": Element[];
    }
    interface PlaitText {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPlaitElementElement extends Components.PlaitElement, HTMLStencilElement {
    }
    var HTMLPlaitElementElement: {
        prototype: HTMLPlaitElementElement;
        new (): HTMLPlaitElementElement;
    };
    interface HTMLPlaitRichtextElement extends Components.PlaitRichtext, HTMLStencilElement {
    }
    var HTMLPlaitRichtextElement: {
        prototype: HTMLPlaitRichtextElement;
        new (): HTMLPlaitRichtextElement;
    };
    interface HTMLPlaitTextElement extends Components.PlaitText, HTMLStencilElement {
    }
    var HTMLPlaitTextElement: {
        prototype: HTMLPlaitTextElement;
        new (): HTMLPlaitTextElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "my-component": HTMLMyComponentElement;
        "plait-element": HTMLPlaitElementElement;
        "plait-richtext": HTMLPlaitRichtextElement;
        "plait-text": HTMLPlaitTextElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PlaitElement {
        "element"?: Element;
    }
    interface PlaitRichtext {
        "value"?: Element[];
    }
    interface PlaitText {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "my-component": MyComponent;
        "plait-element": PlaitElement;
        "plait-richtext": PlaitRichtext;
        "plait-text": PlaitText;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "plait-element": LocalJSX.PlaitElement & JSXBase.HTMLAttributes<HTMLPlaitElementElement>;
            "plait-richtext": LocalJSX.PlaitRichtext & JSXBase.HTMLAttributes<HTMLPlaitRichtextElement>;
            "plait-text": LocalJSX.PlaitText & JSXBase.HTMLAttributes<HTMLPlaitTextElement>;
        }
    }
}
